#:schema ./schema.json

default_model = "gpt-4o-mini"

[[commands]]
command = "gen-config-md"
description = "Generate config.md docs from Config type"
prompt = "Given code:\n```ts\n{{code}}\n```\nUpdate the documentation for the Config type in the code if changes are required, return the markdown only if changes are made, or NONE if unchanged, existing documentation:\n{{config}}"
[commands.variables]
code = "cat src/config.ts"
config = "cat docs/config.md"
